version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: alex_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./database/lineage.db
    volumes:
      - ./backend/database:/app/database

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: alex_frontend
    ports:
      - "8001:8001"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  cli:
    build:
      context: .
      dockerfile: cli/Dockerfile
    container_name: alex_cli
    environment:
      - TRAINLOG_BACKEND=http://backend:8000
      - ALEXANDRIA_BACKEND_URL=http://backend:8000
    volumes:
      - ./tracker:/app/tracker
    tty: true
    stdin_open: true
